name: Release Packaging

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release Packaging
    strategy:
      matrix:
        os: [ubuntu-latest] # windows-latest doesn't really work with rust
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Release Build
        run: cargo build --release
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: intel-chipsim
          path: target/release/intel-chipsim
      - name: 'Add to release'
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/intel-chipsim
